name: Mise à jour Quotidienne

on:
  schedule:
    # 11:00 UTC = 12:00 en France (Hiver) / 13:00 (Eté)
    - cron: '0 11 * * *'
  # Permet aussi de lancer le script manuellement depuis l'interface pour tester
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: pip install -r requirements.txt

      - name: Lancement du script
        run: python newsletter_generator.py

      - name: Sauvegarde et Publication
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Mise à jour quotidienne des marchés" || exit 0
          git push
